environment:
  nodejs_version: 6
  COUCHDB_URL:
    secure: hzgHdrfKK711CWypCDk3aR0YCwyaZ5tsrLUTq/xIHsE=

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install bower
  - node_modules\.bin\bower install

before_build:
  - ps: (Get-Content src\config\example_config.js).replace('%%COUCHDB_URL%%', $env:COUCHDB_URL) | Set-Content src\config\config.js

build_script:
  - node --version
  - npm --version
  - npm run pack:win

test: off

artifacts:
  - path: 'dist-builder\*.exe'

deploy:
  provider: GitHub
  description: "Release description"
  artifact: /.*\.exe/
  auth_token:
    secure: a46cad2b5ba75eb4fa75190abb56c1786c9c9dfb
  draft: false
  prerelease: false
  # Ensure that appveyor does not create another tag!
  tag: $(appveyor_repo_tag_name)
  on:
    branch: master          # Release from this branch only
    appveyor_repo_tag: true # Deploy on tag push only
