# Use container based trusty environment to make nodejs native extensions
# work without extra package installs.
sudo: false
dist: trusty

os:
  - linux
  - osx

language: node_js
node_js:
  - 6

addons:
  apt:
    packages:
      # Needed for electron-builder to process .icns icon image files
      - icnsutils
      - graphicsmagick
      - xz-utils

env:
  global:
    secure: JynpkMZNBW90+1NbHYJuiPHYbXURFOnZKMd/TfXreFJimssVHnMS8SQPm2wnLYXfHKx+lqI5tV3mWj8YdXSs8+yWUC96QEyhZjpJG3NsLzYfTdjh5j/d4/rrHJgDYEiNz9/03PCxFZJ8BWXih+PPcoZNqSWUrAOaRIVrmAKqDKYsteTUY3pVrELfujvZlkE/dnPtmdJwX9KdIpVmDl5SecY/aOHb+ImEAjc7kPf5Gbe3SC1FP22o0nNtWuSpaZiMBIudD2djX8r9214V4I1KCuVK1/lo6DnUBrD9U0SSFe8XHrRSQOr54KXplC+jJlCk3bM1a6QH60EB6eQ77bJQ++kkj1GU4SL+Dswu4OGL6w0lQKL6ey4lNsUPQeIaIydAIoCacE9xEWU+6KZkiLIPOVJlPNKrANV+NMNdBQSCYe8nMSNUhlahmeYsCyEdPg7eXFaRMqDQh1ZjRE/ljdDwi8DW9K1Ne2pfL98w/GxZdkn9doAuLx9pn5DSU5MwSXWkauQvlYHX1ou/tlGGQd0e40FyPH79KDlEPe7J121Wa8OQyJBP0ZBnrPg4LaVgX74fM7An2TSIdbrsR/ZbQLHv9141EYAFx51JJVz08dZYBrI8FuBPi5Wdb3fP3kEQTYMwcyj5H0q9gQndH+P2hM8RFUOkh/zaL1njS3N07M01W6o=

before_script:
  - npm install bower
  - ./node_modules/.bin/bower install
  - sed -e s,%%COUCHDB_URL%%,$COUCHDB_URL,g src/config/example_config.js > src/config/config.js

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run pack:mac   ; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then npm run pack:linux ; fi

deploy:
  provider: releases
  api_key:
    secure: xMS0WBatNJz+XSquXeNeYzLMNf4avk5eBk6O8VHUQ3fQG37bHVbjDaqd/PrvIOgO2tlJdhayIfJYsFPkP5ahVMi7qj4HpM1GU5Lq6jbEvUUyYBGlfhILhS9u5KXMjwvoAJZ0TaOyz3dhJMWX/EOXIMxiaX7fAtLTvFkPgC74dwY9r7vvHnRG20Zc52zEMXBn1OVkmHqxCK7zGfEWrarYD3RImWA6BBl852ncipOY5l7y0yCeRokULzIM9MwQgKNAhZO2ijexZLNdlPk3DDuw+SLWPxSjYoHcadASPp2iBTkV9cKbKs/IRXEdkSFgiV9HFIo4TnJQ7V7sAH8NjwVBJaPxBi2TBEjKWY786fOMu2CJxSkQ4XywicI/5p1SS3Yd60tUvGed38AJWZr0N8f559hLZNHsqehF/8V0r+KBbCkCndOAjdnGrypuJXRpRUsQVw1qD5B5mrvAom/OBaGI/6lIRZkO8GJe1JUvToXV/VvIh00OcgnHVddX1BKnvYVvisI7MadkkukqQbj5WfwHAzZzAQ1wdrD3g5gZjiXO81f1ZGBvrz4le2LBy/amMr+aP5EFuoZwWk4lC9ME5M8ZZR/bcbw6L0UJV+Zj10VNtJFeOPJzbnYC3CojWQkHrqH3F7H+GWBy0pl9Ms98sPItrW2YAL+lMnaya4XuqOmdiKw=
  file_glob: true
  file:
    - "dist-builder/*.AppImage"
    - "dist-builder/*.dmg"
    - "dist-builder/latest.yml"
    - "dist-builder/latest-mac.json"
  skip_cleanup: true
  on:
    tags: true
